apiVersion: apps/v1
kind: Deployment
metadata:
  name: mogul-mvp-be-auth-deployment
  namespace: mogul-dev
  labels:
    app: mogul-mvp-be-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mogul-mvp-be-auth
  template:
    metadata:
      labels:
        app: mogul-mvp-be-auth
    spec:
      volumes:
      - configMap:
          items:
          - key: .env
            path: .env
          name: mogul-mvp-be-auth
        name: dot-env

      containers:
      - name: mogul-mvp-be-auth
        image: 671826480772.dkr.ecr.us-east-1.amazonaws.com/mogul-mvp-be-auth-dev:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: dot-env
          mountPath: /usr/src/app/.env
          name: dot-env
          subPath: .env
